export const routeConfig = {
  // main: "/",
  home: "/",
  women: "/home-page",
  login: "/login",
  signup: "/signup",
  product: "/:slug",
  searchMobile: "/search",
  listProducts: "/clothes",
  frequentlyAskedQuestion: "/faq",
  wardrobe: "/wardrobe",
  wardrobe_lists_liked: "/wardrobe/lists/liked",
  wardrobe_lists_owned: "/wardrobe/lists/owned",
  wardrobe_lists_liked_outfits: "/wardrobe/lists/liked-outfits",
  wardrobe_lists_sell: "/wardrobe/lists/sell",

  // following: "/following",
  // profile: "/@:username",
  // upload: "/upload",
  // search: "/search",
  // live: "/live",
  // media_detail: "/@:username/video/:mediaId",
  not_found: "*",
};
